import { Urbanist } from "next/font/google";
import "./globals.css";
import { register } from 'swiper/element/bundle';

register();
// import 'swiper/css'
// import 'swiper/css/navigation'
// import 'swiper/css/pagination'
// import 'swiper/css/scrollbar'

const urbanist = Urbanist({
  weight: ["400", "600"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-urbanist",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <link rel="icon" href="/images/logo2.svg" sizes="any" />
      <body className={`${urbanist.variable} font-primary`}>
        {children}

        </body>
    </html>
  );
}
